### PR TITLE
feat: packaging and add erfs

### PR DESCRIPTION
**Pull request by Cruise-z**
An easy-to-use, easy-to-setup, hassle-free secure file system with the encrypted data being stored on a remote cloud server without having to trust the server.

Log: packaging and add erfs
Issue: deepin-community/sig-deepin-sysdev-team#227

### CODE REVIEW

**Comment by Cruise-z** [comment]
@Zeno-sole 构建成功，请老师检查：

**Comment by Cruise-z** [comment]
@UTsweetyfish 老师捞捞这个*_*

**Comment by Cruise-z** [comment]
@hudeng-go 老师也看下这个

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
